### Create a user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "asa11@gmail.com",
  "password": "12345678"
}

### Signin as existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "asa1@gmail.com",
  "password": "12345678"
}

### Find a user
GET http://localhost:3000/auth/7

### Find all users with email
GET http://localhost:3000/auth/?email=asa1@gmail.com

### Remove a User
DELETE http://localhost:3000/auth/2

### Update a user
PATCH http://localhost:3000/auth/387987
Content-Type: application/json

{
  "email": "mnf@gmail.com"
}

###
GET http://localhost:3000/auth/whoami

### signOut

POST http://localhost:3000/auth/signout

### reports create

POST http://localhost:3000/reports
content-type: application/json

{
  "make": "Box Chevy 6",
  "model": "Carola",
  "year": 1980,
  "mileage": 10000,
  "lng": 0,
  "lat": 0,
  "price": 500000
}

### Approve
PATCH http://localhost:3000/reports/1
content-type: application/json

{
  "approved": true
}

### Get an estimate
GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=20000&year=2000
content-type: application/json